indexes for mysql schema dump
basilfx/phinx pull request #1
Opened 2016-10-30 00:31 UTC by jwh315

I ran across your schema dump/load feature for phinx a few weeks ago.  I really love your implementation but really needed indexes.  I was able to get the indexes put into the mysql adapter pretty easily.  

I have a pretty decent size dev database (over 700 tables) at my company, that has an array of ridiculous design inconsistencies from years of development.  The indexing seems to be recreating tables 100% from their original state, so I am fairly confident that I have covered most edge cases related to indexing and phinx.

Not sure if you would be interested in merging this branch into yours, or if you would need more from my end before doing so.

Either way, thanks for the effort putting this schema dumper together, it has saved me several hours worth of work.

2016-11-02 12:29 UTC, basilfx commented
Sounds like a great addition! Let me take a look at it.

2016-11-10 06:41 UTC, basilfx requested changes

2016-11-10 06:41 UTC, basilfx commented on src/Phinx/Db/Adapter/AdapterInterface.php
> +    const PHINX_TYPE_DOUBLE         = 'double';
I think this would be better in a separate PR.

2016-11-10 06:41 UTC, basilfx commented on src/Phinx/Db/Adapter/MysqlAdapter.php
> +            case static::PHINX_TYPE_DOUBLE:
I think this would be better in a separate PR.

2016-11-10 06:41 UTC, basilfx commented on src/Phinx/Db/Adapter/MysqlAdapter.php
> +    public function getIndexes($tableName, $lowercase = true)
What's the added benefit of lowercase?

2016-11-10 06:42 UTC, basilfx commented
Can you also rebase (interactively) to fixup 2d8ebb3 in 8904d29?

2016-11-11 04:50 UTC, jwh315 commented on src/Phinx/Db/Adapter/MysqlAdapter.php
> +    public function getIndexes($tableName, $lowercase = true)
this method was originally lowercasing all index column names (as it is currently).  I initially thought I needed to have case sensitive column names for mysql on some operating systems.  That turned out to be incorrect thinking on my part.  I have removed the extra param

2016-11-11 04:52 UTC, jwh315 commented
I removed the DOUBLE column type and fixed the commit history to remove the superfluous commit.  I also noticed another issue that needed to be addressed for tables that do not have primary keys, that has been fixed in the most recent commit.

2016-11-12 11:59 UTC, merged

2016-11-12 12:00 UTC, basilfx commented
Looks good to me, thanks!

2016-11-12 12:55 UTC, basilfx commented
I made a [few improvements](https://github.com/basilfx/phinx/commit/1bb96f37fa1a9164d7289c4e2969f3f1221610e3) to the code:

- There was still a reference to double in the PDOAdapter
- Undefined index check
- Optimized template

Other than that, it works great :-)

2016-11-14 14:52 UTC, futoase commented on src/Phinx/Migration/Schema/Schema.template.php
> +            <? if ($name !== 'PRIMARY'): ?>
``` php
<?php if ($name !== 'PRIMARY'): ?>
```

2016-11-18 13:03 UTC, basilfx commented on src/Phinx/Migration/Schema/Schema.template.php
> +            <? if ($name !== 'PRIMARY'): ?>
Fixed, thanks!

2016-11-18 13:06 UTC, basilfx commented
@jwh315 I have fixed some more:

* 84cc9b7d48ba5e4a377815ccb80befebbbc00ee8 reverts another change that should not be part of this fork.
* 926918f64559eee8cf2be42a0c99bcf8006541e0 column names should not be converted to lower case, just interpret them as returned by MySQL's `SHOW INDEXES`.
* 322eedf9e9affa0551a9d543456065e2f2daab4d fixes a problem with the code generation: in `buildIndexString` the `$name` parameter caused issues. In SQLite, the name of an index cannot match a column name. I remove this parameter, but added it back as an option of the `Index` class.